### ISSUE TITLE
Example Deployment should set deployment strategy to Recreate

### ISSUE THREAD

**Issue by GrahamDumpleton** [zalando-incubator/kopf#116]
Docs at:

https://kopf.readthedocs.io/en/latest/deployment/

have `Deployment` example of:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kopfexample-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kopfexample-operator
  template:
    metadata:
      labels:
        application: kopfexample-operator
    spec:
      serviceAccountName: kopfexample-account
      containers:
      - name: the-only-one
        image: nolar/kopf-operator
```

This should also set `.spec.strategy.type==Recreate`.

https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#recreate-deployment

This is because the default for deployment strategy is rolling update, which means that on a re-deployment triggered by a change to pod template, there can be two instances of the pod at the same time. That is, the new pod is started before the old is shutdown.

The docs say to only ever set replicas to 1 due to issue of there being more than once instance, but the rolling update can induce the same problem. You should therefore set the deployment strategy to `Recreate` to ensure old pod is shutdown before starting new one, thus ensuring there is truly only at most one pod for the operator running at the same time.
