### ISSUE TITLE
Field handlers are not triggered with overly specific fields

### ISSUE THREAD

**Issue by nolar** [zalando-incubator/kopf#190]
## Expected Behavior

The field handler should handle all the relevant field changes, no matter what else is changed, or from which original state.

## Actual Behavior

The handler is only triggered when a deeply nested specific field is changed/added/removed, but not when the whole structure that contains it is added/changed/removed.

## Steps to reproduce

```python
import kopf

@kopf.on.field('zalando.org', 'v1', 'kopfexamples', field='spec.field')
def fn(**kwargs):
    pass
```

Example original object (note the absence of `spec`!):

```yaml
apiVersion: zalando.org/v1
kind: KopfExample
metadata:
  name: kopf-example-1
```

Changed object:

```yaml
apiVersion: zalando.org/v1
kind: KopfExample
metadata:
  name: kopf-example-1
spec:
  field: value
```

## Specifications

```
kopf==0.21
```
